version: "3"
services:

  node:
    build: .
    container_name: task_runner
    tty: true
    environment:
      NODE_ENV: docker_dev
    volumes:
      - ./:/app
      - sass_lesson_node_modules:/app/node_modules

volumes:
  sass_lesson_node_modules: